<?php
/**
 * Update blog page (ID 26038) post_content with featured card CSS improvements.
 */

defined( 'ABSPATH' ) || exit;

return [
	'description' => 'Update blog listing page featured card layout and section padding.',

	'up' => function (): string {
		$content = <<<'CONTENTBLOCK'
<div class="bg-center bg-cover flex items-center section theme-dark md:h-4xl tbst-bg-image" data-pb-label="Section" style="background-image: url('SITE_URL_PLACEHOLDER/wp-content/uploads/2025/02/DR-background-1.jpg');"> <div class="container" data-pb-label="Container"> <div class="column" data-pb-label="Column"> <div class="content-block max-w-3xl" data-pb-label="Content Block"> <h1 class="">Articles  </h1> <p class=" ">Read the Care collection of curated short pieces offering advice and guidance on a range of relevant topics.  </p> </div> </div> </div> </div> <div class="section pb-0 pt-10 md:pt-16 md:pb-8" data-pb-label="Section"> <div class="container" data-pb-label="Container"> <div class="column" data-pb-label="Column"> <div class="content-block" data-pb-label="Content Block"> <!-- spinnr:eyJpZCI6InBiLWVsZW1lbnQtd3AtcG9zdC1saXN0LTUyIiwibGFiZWwiOiJ3cC1wb3N0LWxpc3QiLCJlbGVtZW50Ijoid3AtcG9zdC1saXN0IiwiY2hpbGRyZW4iOltdLCJwYl9hdHRyaWJ1dGVzIjp7ImNsYXNzIjoiIiwic3R5bGUiOiIifSwicGJfY29tcG9uZW50X2RhdGEiOnsidHlwZSI6InBvc3RzIiwib3JkZXJieSI6ImRhdGUiLCJvcmRlciI6ImRlc2MiLCJjYXRlZ29yaWVzIjoiIiwidGFncyI6IiIsImxpbWl0IjoiMSIsIm9mZnNldCI6MCwiZGlzcGxheV90eXBlIjoibm9ybWFsIiwiZmlsdGVyX3VpIjoiZHJvcGRvd24iLCJmaWx0ZXJzIjpbXSwib3B0aW9ucyI6eyJsb29wIjp0cnVlLCJtYXJnaW4iOjAsImF1dG9wbGF5IjpmYWxzZSwiYXV0b3BsYXlUaW1lb3V0Ijo1MDAwLCJhdXRvcGxheUhvdmVyUGF1c2UiOmZhbHNlLCJuYXYiOnRydWUsInJlc3BvbnNpdmUiOnsiMCI6eyJpdGVtcyI6MX0sIjc2OCI6eyJpdGVtcyI6Mn0sIjk5MiI6eyJpdGVtcyI6M30sIjEyMDAiOnsiaXRlbXMiOjR9fX0sInBlcl9wYWdlIjo2LCJjb250YWluZXJfY2xhc3MiOiIiLCJyb3dfY2xhc3MiOiIiLCJjb2x1bW5fY2xhc3MiOiJncmlkIG1kOmdyaWQtY29scy0yIGl0ZW1zLWNlbnRlciBib3JkZXIgYm9yZGVyLXN0cm9rZSByb3VuZGVkLXhsIiwiY2FyZF9mb3JtYXQiOiI8ZGl2IGNsYXNzPVwiaC1mdWxsXCI+PGltZyBjbGFzcz1cIm9iamVjdC1jb3ZlciBoLWZ1bGxcIiBzcmM9XCJ7e2ZlYXR1cmVkX2ltYWdlX3VybH19XCIgYWx0PVwie3t0aXRsZS5yZW5kZXJlZH19XCIgXC8+PFwvZGl2PlxuPGRpdiBjbGFzcz1cImNhcmQtYm9keSBtZDpweS01eGxcIj5cbiAgICAgICAgIDxoNCBjbGFzcz1cInByLXhsXCI+e3t0aXRsZS5yZW5kZXJlZH19PFwvaDQ+XG4gICAgICAgICA8YSBjbGFzcz1cImJ0biBjdGFcIiBocmVmPVwie3tsaW5rfX1cIj5SZWFkIG1vcmU8XC9hPlxuPFwvZGl2PlxuIiwiY2F0X3RheG9ub215X3Rlcm0iOiJjYXRlZ29yeSIsInRhZ190YXhvbm9teV90ZXJtIjoiIiwiYnV0dG9uX2NvbnRhaW5lcl9jbGFzcyI6IiIsImJ1dHRvbl9jbGFzcyI6ImJ0biBjdGEiLCJidXR0b25fdGV4dCI6IlNob3cgbW9yZSJ9LCJkcmFnZ2FibGUiOnRydWUsImRyb3BwYWJsZSI6dHJ1ZX0=  --> <div> [wp-post-list id="pb-element-wp-post-list-52" type="posts" categories="" tags="" orderby="date" order="desc" display_type="normal" container_class="" row_class="" column_class="grid md:grid-cols-2 items-start gap-0 border border-stroke rounded-xl overflow-hidden" cat_taxonomy_term="category" tag_taxonomy_term="" per_page="1" offset="0"]<div class="overflow-hidden"><img class="w-full h-auto block mb-0" style="margin-bottom:0" src="{{featured_image_url}}" alt="{{title.rendered}}" /></div>
<div class="self-start lg:self-auto w-full px-4 pt-3 md:px-6 lg:py-6 flex flex-col md:block">
         <h5 class="pr-xl md:text-base lg:text-2xl">{{title.rendered}}</h5>
         <a class="btn cta mt-1 md:mt-2 self-end md:self-auto" href="{{link}}">Read more</a>
</div>
[/wp-post-list]</div> </div> </div> </div> </div> <div class="section xl:bg-secondary md:pt-8" data-pb-label="Section"> <div class="container grid lg:grid-cols-3 md:grid-cols-2" data-pb-label="Container"> <div class="column col-span-full" data-pb-label="Column"> <div class="content-block" data-pb-label="Content Block"> <!-- spinnr:eyJpZCI6InBiLWVsZW1lbnQtd3AtcG9zdC1saXN0LTYxNi0yNyIsImxhYmVsIjoid3AtcG9zdC1saXN0IiwiZWxlbWVudCI6IndwLXBvc3QtbGlzdCIsImNoaWxkcmVuIjpbXSwicGJfYXR0cmlidXRlcyI6eyJjbGFzcyI6IiIsInN0eWxlIjoiIn0sInBiX2NvbXBvbmVudF9kYXRhIjp7InR5cGUiOiJwb3N0cyIsIm9yZGVyYnkiOiJkYXRlIiwib3JkZXIiOiJkZXNjIiwiY2F0ZWdvcmllcyI6IiIsInRhZ3MiOiIiLCJsaW1pdCI6IjI0Iiwib2Zmc2V0IjoiMSIsImRpc3BsYXlfdHlwZSI6Im5vcm1hbCIsImZpbHRlcl91aSI6ImRyb3Bkb3duIiwiZmlsdGVycyI6WyJjYXRlZ29yeSJdLCJvcHRpb25zIjp7Imxvb3AiOnRydWUsIm1hcmdpbiI6MCwiYXV0b3BsYXkiOmZhbHNlLCJhdXRvcGxheVRpbWVvdXQiOjUwMDAsImF1dG9wbGF5SG92ZXJQYXVzZSI6ZmFsc2UsIm5hdiI6dHJ1ZSwicmVzcG9uc2l2ZSI6eyIwIjp7Iml0ZW1zIjoxfSwiNzY4Ijp7Iml0ZW1zIjoyfSwiOTkyIjp7Iml0ZW1zIjozfSwiMTIwMCI6eyJpdGVtcyI6NH19fSwicGVyX3BhZ2UiOjYsImNvbnRhaW5lcl9jbGFzcyI6IiIsInJvd19jbGFzcyI6ImdyaWQgbGc6Z3JpZC1jb2xzLTMgbWQ6Z3JpZC1jb2xzLTIiLCJjb2x1bW5fY2xhc3MiOiJjYXJkIiwiY2FyZF9mb3JtYXQiOiI8YSBjbGFzcz1cIm5vLXVuZGVybGluZSBtYi0wXCIgaHJlZj1cInt7bGlua319XCIgdGFyZ2V0PVwiX2JsYW5rXCI+PGltZyBjbGFzcz1cInctZnVsbCBoLTN4bCBvYmplY3QtY292ZXJcIiBzcmM9XCJ7e2ZlYXR1cmVkX2ltYWdlX3VybH19XCIgYWx0PVwie3t0aXRsZS5yZW5kZXJlZH19XCIgXC8+XG4gICAgICAgICAgPGRpdiBjbGFzcz1cImNhcmQtYm9keSBcIj5cbiAgICAgICAgICAgICAgICAgICAgPGg1IGNsYXNzPVwibm8tdW5kZXJsaW5lXCI+e3t0aXRsZS5yZW5kZXJlZH19IFxuICAgICAgICAgICAgICAgICAgICA8XC9oNT5cbiAgICAgICAgICAgICAgPHAgY2xhc3M9XCJ0ZXh0LWFjY2VudCBmb250LW1lZGl1bSB1bmRlcmxpbmVcIj5SZWFkIG1vcmU8XC9wPlxuICAgICAgICAgIDxcL2Rpdj48XC9hPlxuIiwiY2F0X3RheG9ub215X3Rlcm0iOiJjYXRlZ29yeSIsInRhZ190YXhvbm9teV90ZXJtIjoiIiwiYnV0dG9uX2NvbnRhaW5lcl9jbGFzcyI6IiIsImJ1dHRvbl9jbGFzcyI6ImJ0biBjdGEiLCJidXR0b25fdGV4dCI6IlNob3cgbW9yZSJ9LCJkcmFnZ2FibGUiOnRydWUsImRyb3BwYWJsZSI6dHJ1ZX0=  --> <div> [wp-post-list id="pb-element-wp-post-list-616-27" type="posts" categories="" tags="" orderby="date" order="desc" display_type="normal" container_class="" row_class="grid lg:grid-cols-3 md:grid-cols-2" column_class="card" cat_taxonomy_term="category" tag_taxonomy_term="" per_page="24" offset="1"]<a class="no-underline mb-0" href="{{link}}" target="_blank"><img class="w-full h-3xl object-cover" src="{{featured_image_url}}" alt="{{title.rendered}}" />
          <div class="card-body ">
                    <h5 class="no-underline">{{title.rendered}} 
                    </h5>
              <p class="text-accent font-medium underline">Read more</p>
          </div></a>
[/wp-post-list]</div> </div> </div> </div> </div> <div class="section" data-pb-label="Section"> <div class="container grid lg:grid-cols-3 md:grid-cols-2" data-pb-label="Container"> <div class="column col-span-full" data-pb-label="Column"> <div class="content-block" data-pb-label="Content Block"> <h2 class=" ">What are others saying?  </h2> </div> </div> <div class="border border-stroke column rounded-xl" data-pb-label="Column"> <div class="bg-secondary content-block p-4 rounded-t-xl" data-pb-label="Content Block"> <img src="SITE_URL_PLACEHOLDER/wp-content/uploads/2022/08/Murine-Dry-Eye-how-aware-are-you..jpg" class="h-3xl mx-auto mb-0" alt="" /> </div> <div class="content-block p-4" data-pb-label="Content Block"> <p class="font-medium text-paragraph no-underline">Medical Republic  </p> <h5 class="no-underline">HCP – Dry Eye – How aware are you?  </h5><a class="space-x-3" href="https://www.medicalrepublic.com.au/dry-eyes-how-aware-are-you/6012" target="_self">Read more <i class="fa-solid fa-right-from-bracket"></i></a> </div> </div> <div class="border border-stroke column rounded-xl" data-pb-label="Column"> <div class="bg-secondary content-block p-4 rounded-t-xl" data-pb-label="Content Block"> <img src="SITE_URL_PLACEHOLDER/wp-content/uploads/2022/08/Murine-managing-dry-eyes-in-general-practice.jpg" class="h-3xl mx-auto mb-0" alt="" /> </div> <div class="content-block p-4" data-pb-label="Content Block"> <p class="font-medium text-paragraph no-underline">Medical Republic  </p> <h5 class="no-underline">HCP – Managing Dry Eye in General Practice  </h5><a class="space-x-3" href="https://www.medicalrepublic.com.au/managing-dry-eyes-in-general-practice/4556" target="_self">Read more <i class="fa-solid fa-right-from-bracket"></i></a> </div> </div> </div> </div> <div class="bg-secondary pb-0 pt-0 section mt-6xl" data-pb-label="Section"> <div class="container grid mt-xl" data-pb-label="Container"> <div class="-mt-4xl bg-center bg-cover col-span-full column md:flex md:p-md md:p-xl p-lg rounded-md theme-dark" data-pb-label="Column" style="background-image: url('SITE_URL_PLACEHOLDER/wp-content/uploads/2025/02/CTA-background-small.png');"> <div class="content-block items-center mx-auto" data-pb-label="Content Block"><a class="border btn cta my-0 px-4xl shadow-xl border-accent-hover" href="/resources" target="_self">Explore Clinical Resources</a> </div> </div> </div> </div>
CONTENTBLOCK;

		$content = str_replace( 'SITE_URL_PLACEHOLDER', home_url(), $content );

		$result = wp_update_post( [
			'ID'           => 26038,
			'post_content' => $content,
		], true );

		if ( is_wp_error( $result ) ) {
			throw new \RuntimeException( 'Failed to update blog page: ' . $result->get_error_message() );
		}

		return 'Blog page (ID 26038) featured card content updated.';
	},
];
